SELECT * FROM zim_afro_t10.players;
use zim_afro_t10;
alter table players drop nationality;
-- values
INSERT INTO `zim_afro_t10`.`players	` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('001', 'Avishka Fernando', '26', 'NYS Lagos', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('002', 'Dion Mysers', '22', 'NYS Lagos', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('003', 'Najibullah Zadran', '31', 'NYS Lagos', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('004', 'Rassie van der Dussen', '35', 'NYS Lagos', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('005', 'Joshua Bishop', '24', 'NYS', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('006', 'Ryan Burl', '30', 'NYS Lagos', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('007', 'Thisara Perera', '35', 'NYS Lagos', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('008', 'Clive Madande', '24', 'NYS Lagos', 'WC_batsman');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('009', 'Nyasha Mayavo', '21', 'NYS Lagos', 'WC_batsman');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('010', 'Akhilesh Reddy', '24', 'NYS Lagos', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('011', 'Binura Fernando', '29', 'NYS Lagos', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('012', 'Blessing Muzarabani', '27', 'NYS Lagos', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('013', 'Kaveesh Sathsara', '21', 'NYS Lagos ', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('014', 'Matiullah Khan', '31', 'NYS Lagos', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('015', 'Newman Nyamhuri', '18', 'NYS Lagos', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('016', 'Oshane Thomas', '27', 'NYS Lagos', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('017', 'David Warner', '37', 'Bulawayo Brave Jaguars', 'Batsman');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('018', 'Kirk Mckenzie ', '23', 'Bulawayo Brave Jaguars', 'Batsman');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('019', 'Kobe Herft', '21', 'Bulawayo Brave Jaguars', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('020', 'Laurie Evans', '36', 'Bulawayo Brave Jaguars', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('021', 'Nick Hobson', '30', 'Bulawayo Brave Jaguars', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('022', 'Carlos Brathwaite', '36', 'Bulawayo Brave Jaguars', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('023', 'Victor Chirwa', '20', 'Bulawayo Brave Jaguars', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('024', 'Vihas Thewmiika', '18', 'Bulawayo Brave Jaguars', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('025', 'Wessly Madhavere', '23', 'Bulawayo Brave Jaguars', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('026', 'Anamul Haque', '31', 'Bulawayo Brave Jaguars', 'WC_Batsman');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('027', 'Panashe Taruvunga', '18', 'Bulawayo Brave Jaguars', 'WC_Batsman');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('028', 'Akila Danajaya', '30', 'Bulawayo Brave Jaguars', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('029', 'Brad Evans', '27', 'Bulawayo Brave Jaguars', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('030', 'Daryn Dupavillon', '30', 'Bulawayo Brave Jaguars', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('031', 'Richard Ngarava', '26', 'Bulawayo Brave Jaguars', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('032', 'Sabir Ali', '33', 'Bulawayo Brave Jaguars', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('033', 'Wellingtion Masakadza', '30', 'Bulawayo Brave Jaguars', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('034', 'Charith Asalanka', '27', 'Joburg Bangala Tigers', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('035', 'Chris Lynn', '34', 'Joburg Bangala Tigers', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('036', 'Hazratullah Zazai', '26', 'Joburg Bangala Tigers', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('037', 'Johnanthan Campbell', '26', 'Joburg Bangala Tigers', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('038', 'Kimani Melius', '23', 'Joburg Bangala Tigers', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('039', 'Antum Naqvi', '25', 'Joburg Bangala Tigers', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('040', 'George Linde', '33', 'Joburg Bangala Tigers', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('041', 'Karim Janat', '26', 'Joburg Bangala Tigers', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('042', 'Sikandar Raza', '38', 'Joburg Bangala Tigers', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('043', 'Tashinga Musekiwa', '28', 'Joburg Bangala Tigers', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('044', 'Kusal Perera', '34', 'Joburg Bangala Tigers', 'WC_Batsman');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('045', 'Mohammed Shahzad', '37', 'Joburg Bangala Tigers', 'WC_Batsman');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('046', 'Adam Milne', '32', 'Joburg Bangala Tigers', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('047', 'Kevin Koththigoda', '25', 'Joburg Bangala Tigers', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('048', 'Luke Wood', '29', 'Joburg Bangala Tigers', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('049', 'Tendai Chatara', '33', 'Joburg Bangala Tigers', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('050', 'Tinashe Muchawaya', '27', 'Joburg Bangala Tigers', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('051', 'Colin Munro', '37', 'Durban Wolves', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('052', 'Emmanuvel Bawa', '20', 'Durban Wolves', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('053', 'Innocent kala', '32', 'Durban Wolves', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('054', 'Mark Chapman', '30', 'Durban Wolves', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('055', 'Mbeki Joseph', '23', 'Durban Wolves', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('056', 'Sharjeel Khan', '35', 'Durban Wolves', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('057', 'Will Smeed', '22', 'Durban Wolves', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('058', 'Kashif Daud', '38', 'Durban Wolves', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('059', 'Raveen de Silva ', '21', 'Durban Wolves', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('060', 'Tinotenda Maposa', '21', 'Durban Wolves', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('061', 'Regis Chakbawa', '36', 'Durban Wolves', 'WC_Batsman');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('062', 'Richmond Mutumbami', '25', 'Durban Wolves', 'WC_Batsman');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('063', 'Dawlat Zadran', '36', 'Durban Wolves', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('064', 'Donald Tiripano', '36', 'Durban Wolves', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('065', 'Mohammed Ifran', '42', 'Durban Wolves', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('066', 'Muhammad Rohid Khan', '21', 'Durban Wolves', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('067', 'Yashir Shah', '38', 'Durban Wolves', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('068', 'Ben Curran', '28', 'Cape Town Samp Army', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('069', 'Brian Chari', '32', 'Cape Town Samp Army', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('070', 'Dawid Malan', '36', 'Cape Town Samp Army', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('071', 'Jack Taylor', '32', 'Cape Town Samp Army', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('072', 'Milton Shumba', '23', 'Cape Town Samp Army', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('073', 'Tadiwanashe Marumani', '22', 'Cape Town Samp Army', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('074', 'Brian Bennett', '20', 'Cape Town Samp Army', 'All-Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('075', 'David Willey ', '34', 'Cape Town Samp Army', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('076', 'Gulbadin Naib ', '33', 'Cape Town Samp Army', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('077', 'Rohan Mustafa', '35', 'Cape Town Samp Army', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('078', 'Sineth Jayawardena', '19', 'Cape Town Samp Army', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('079', 'Adam Rossington', '31', 'Cape Town Samp Army', 'WC_Batsman');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('080', 'Leonardo Julien', '22', 'Cape Town Samp Army', 'WC_Batsman');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('081', 'Amir Hamza', '33', 'Cape Town Samp Army', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('082', 'Nicholson Gordon', '32', 'Cape Town Samp Army', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('083', 'Qais Ahmed', '24', 'Cape Town Samp Army', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('084', 'Salman Irshad', '28', 'Cape Town Samp Army', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('085', 'Tawanda Maposa', '23', 'Cape Town Samp Army', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('086', 'Geroge Munsey', '31', 'Harare Bolts', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('087', 'Janishka Perera', '23', 'Harare Bolts', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('088', 'Micheal Palmer', '19', 'Harare Bolts', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('089', 'Sabbir Rahman', '32', 'Harare Bolts', 'Batter');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('090', 'Brandon Mavuta', '27', 'Harare Bolts', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('091', 'Dasun Shanaka', '32', 'Harare Bolts', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('092', 'Faraz Akram', '30', 'Harare Bolts', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('093', 'James Neesham', '33', 'Harare Bolts', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('094', 'Sean Williams', '37', 'Harare Bolts', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('095', 'Shehan Jayasuriya', '32', 'Harare Bolts', 'All_Rounder');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('096', 'Kennar Lewis', '33', 'Harare Bolts', 'WC_Batsman');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('097', 'Lahiru Milantha', '30', 'Harare Bolts', 'WC_Batsman');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('098', 'Aftab Alam', '31', 'Harare Bolts', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('099', 'Alex Falso', '20', 'Harare Bolts', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('100', 'Arinesto Vezha', '26', 'Harare Bolts', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('101', 'Luke Jongwe', '29', 'Harare Bolts', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('102', 'Richard Glesson', '36', 'Harare Bolts', 'Bowler');
INSERT INTO `zim_afro_t10`.`players` (`player_id`, `player_name`, `age`, `team`, `role`) VALUES ('103', 'Trevor Gwandu', '26', 'Harare Bolts', 'Bowler');


-- update 

UPDATE `zim_afro_t10`.`players` SET `team` = 'NYS Lagos' WHERE (`player_id` = '5');
UPDATE `zim_afro_t10`.`players` SET `role` = 'WC_Batsman' WHERE (`player_id` = '8');
UPDATE `zim_afro_t10`.`players` SET `role` = 'WC_Batsman' WHERE (`player_id` = '9');
